In [ ]:
import numpy as np # Import the NumPy library, commonly aliased as np

In [ ]:
from time import process_time # Import the process_time function from the time module to measure CPU time

Time taken by a list

In [ ]:
python_list = [i for i in range (10000)]

start_time = process_time() # Record the start time

python_list = [i+5 for i in python_list] # Perform element-wise addition

end_time = process_time() # Record the end time

print(end_time - start_time) # Print the elapsed CPU time

0.001150787000000042


In [ ]:
np_array = np.array ([i for i in range (10000)]) # Create a NumPy array

start_time = process_time() # Record the start time

np_array += 5 # Perform element-wise addition using NumPy's optimized operations

end_time = process_time() # Record the end time

print(end_time - start_time) # Print the elapsed CPU time

0.0010752579999999679


**Numpy Arrays **

In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
print(type(list1)) # Print the type of the variable (should be list)

[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
np_array = np.array([1,2,3,4,5]) # Create a NumPy array
print(np_array)
print(type(np_array)) # Print the type of the variable (should be numpy.ndarray)

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# creating a 1 dim array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
b = np.array ([(1,2,3,4,5),(6,7,8,9,10)])
print(b)
type(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


numpy.ndarray

In [ ]:
b.shape          # We have 2 rows 5 coloms in this case

(2, 5)

In [ ]:
 c = np.array ([(1,2,3,4),(4,5,6,7)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [4. 5. 6. 7.]]


In [ ]:
c.shape

(2, 4)

Initaial Placeholders in numpy arrays

In [ ]:
# create a numpy array of Zeros
x = np.zeros((4,5))            #4 rows 5 coloms
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones
y= np.ones((3,3))
print(y)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular values

z = np.full((8,9),99)
print(z)


[[99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99]]


In [ ]:
# Create an identity matrix

a = np.eye(5)
print(a)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values

b= np.random.random((3,4))                 #all the time values will be between 0 to 1
print(b)

[[0.96709629 0.63173484 0.79766573 0.34769439]
 [0.93916923 0.94985986 0.39579847 0.81613429]
 [0.17285081 0.85091127 0.79252829 0.75143405]]


In [ ]:
#  random integer values

c = np.random.randint(10,100,(3,5))
print(c)

[[74 11 10 57 79]
 [49 95 54 34 33]
 [56 20 41 79 95]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required

d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[82 61 55 84 73]
 [35 80 11 50 35]
 [86 81 76 60 36]
 [41 49 67 56 73]
 [45 30 72 40 85]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[1 3 5]
 [8 6 6]
 [1 1 0]]
[[12 11 10]
 [11 16 11]
 [12 19 13]]


In [ ]:
# number of dimensions
print(a.ndim)

2


**Array** Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 4 8]
 [0 5 3]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 6]
 [1 3]
 [1 6]]
(3, 2)


In [ ]:
# Generate a new random 2x3 array for demonstration
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 8 4]
 [8 8 9]]
(2, 3)


In [ ]:
# Transpose the array using the .T attribute
trans2 = array.T
print(trans2)
print(trans2.shape)

[[1 8]
 [8 8]
 [4 9]]
(3, 2)


In [ ]:
# Reshaping an array
# Original array with shape (2,3)
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 5 0]
 [4 3 8]]
(2, 3)


In [ ]:
# Reshape the array 'a' to a new shape (3,2)
b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 5]
 [0 4]
 [3 8]]
(3, 2)
